export const team_lib = [
        { "team": "Arizona Cardinals", "sport": "NFL", "region": "W", "color_1": "Crimson", "color_2": "Black" },
        { "team": "Atlanta Falcons", "sport": "NFL", "region": "S", "color_1": "Red", "color_2": "Black" },
        { "team": "Baltimore Ravens", "sport": "NFL", "region": "NE", "color_1": "Purple", "color_2": "Black" },
        { "team": "Buffalo Bills", "sport": "NFL", "region": "NE", "color_1": "RoyalBlue", "color_2": "Red" },
        { "team": "Carolina Panthers", "sport": "NFL", "region": "S", "color_1": "Black", "color_2": "DeepSkyBlue" },
        { "team": "Chicago Bears", "sport": "NFL", "region": "MW", "color_1": "Navy", "color_2": "Orange" },
        { "team": "Cincinnati Bengals", "sport": "NFL", "region": "MW", "color_1": "Orange", "color_2": "Black" },
        { "team": "Cleveland Browns", "sport": "NFL", "region": "MW", "color_1": "SaddleBrown", "color_2": "DarkOrange" },
        { "team": "Dallas Cowboys", "sport": "NFL", "region": "S", "color_1": "Navy", "color_2": "Silver" },
        { "team": "Denver Broncos", "sport": "NFL", "region": "W", "color_1": "DarkOrange", "color_2": "Navy" },
        { "team": "Detroit Lions", "sport": "NFL", "region": "MW", "color_1": "DeepSkyBlue", "color_2": "Silver" },
        { "team": "Green Bay Packers", "sport": "NFL", "region": "MW", "color_1": "ForestGreen", "color_2": "Gold" },
        { "team": "Houston Texans", "sport": "NFL", "region": "S", "color_1": "Navy", "color_2": "Red" },
        { "team": "Indianapolis Colts", "sport": "NFL", "region": "MW", "color_1": "RoyalBlue", "color_2": "White" },
        { "team": "Jacksonville Jaguars", "sport": "NFL", "region": "S", "color_1": "Teal", "color_2": "Black" },
        { "team": "Kansas City Chiefs", "sport": "NFL", "region": "MW", "color_1": "Red", "color_2": "Gold" },
        { "team": "Las Vegas Raiders", "sport": "NFL", "region": "W", "color_1": "Black", "color_2": "Silver" },
        { "team": "Los Angeles Chargers", "sport": "NFL", "region": "W", "color_1": "RoyalBlue", "color_2": "Gold" },
        { "team": "Los Angeles Rams", "sport": "NFL", "region": "W", "color_1": "RoyalBlue", "color_2": "Gold" },
        { "team": "Miami Dolphins", "sport": "NFL", "region": "S", "color_1": "Teal", "color_2": "Orange" },
        { "team": "Minnesota Vikings", "sport": "NFL", "region": "MW", "color_1": "Purple", "color_2": "Gold" },
        { "team": "New England Patriots", "sport": "NFL", "region": "NE", "color_1": "Navy", "color_2": "Red" },
        { "team": "New Orleans Saints", "sport": "NFL", "region": "S", "color_1": "Black", "color_2": "Gold" },
        { "team": "New York Giants", "sport": "NFL", "region": "NE", "color_1": "RoyalBlue", "color_2": "Red" },
        { "team": "New York Jets", "sport": "NFL", "region": "NE", "color_1": "ForestGreen", "color_2": "White" },
        { "team": "Philadelphia Eagles", "sport": "NFL", "region": "NE", "color_1": "ForestGreen", "color_2": "Black" },
        { "team": "Pittsburgh Steelers", "sport": "NFL", "region": "NE", "color_1": "Black", "color_2": "Gold" },
        { "team": "San Francisco 49ers", "sport": "NFL", "region": "W", "color_1": "Crimson", "color_2": "Gold" },
        { "team": "Seattle Seahawks", "sport": "NFL", "region": "W", "color_1": "Navy", "color_2": "Lime" },
        { "team": "Tampa Bay Buccaneers", "sport": "NFL", "region": "S", "color_1": "Crimson", "color_2": "Black" },
        { "team": "Tennessee Titans", "sport": "NFL", "region": "S", "color_1": "RoyalBlue", "color_2": "DeepSkyBlue" },
        { "team": "Washington Commanders", "sport": "NFL", "region": "NE", "color_1": "maroon", "color_2": "Gold" },
        { "team": "Atlanta Hawks", "sport": "NBA", "region": "S", "color_1": "Red", "color_2": "Black" },
        { "team": "Boston Celtics", "sport": "NBA", "region": "NE", "color_1": "Green", "color_2": "White" },
        { "team": "Brooklyn Nets", "sport": "NBA", "region": "NE", "color_1": "Black", "color_2": "White" },
        { "team": "Charlotte Hornets", "sport": "NBA", "region": "S", "color_1": "Teal", "color_2": "Purple" },
        { "team": "Chicago Bulls", "sport": "NBA", "region": "MW", "color_1": "Red", "color_2": "Black" },
        { "team": "Cleveland Cavaliers", "sport": "NBA", "region": "MW", "color_1": "maroon", "color_2": "Gold" },
        { "team": "Dallas Mavericks", "sport": "NBA", "region": "S", "color_1": "Navy", "color_2": "RoyalBlue" },
        { "team": "Denver Nuggets", "sport": "NBA", "region": "W", "color_1": "Navy", "color_2": "Gold" },
        { "team": "Detroit Pistons", "sport": "NBA", "region": "MW", "color_1": "RoyalBlue", "color_2": "Red" },
        { "team": "Golden State Warriors", "sport": "NBA", "region": "W", "color_1": "RoyalBlue", "color_2": "Gold" },
        { "team": "Houston Rockets", "sport": "NBA", "region": "S", "color_1": "Red", "color_2": "Black" },
        { "team": "Indiana Pacers", "sport": "NBA", "region": "MW", "color_1": "Navy", "color_2": "Gold" },
        { "team": "Los Angeles Clippers", "sport": "NBA", "region": "W", "color_1": "Red", "color_2": "RoyalBlue" },
        { "team": "Los Angeles Lakers", "sport": "NBA", "region": "W", "color_1": "Purple", "color_2": "Gold" },
        { "team": "Memphis Grizzlies", "sport": "NBA", "region": "S", "color_1": "Navy", "color_2": "Teal" },
        { "team": "Miami Heat", "sport": "NBA", "region": "S", "color_1": "Red", "color_2": "Black" },
        { "team": "Milwaukee Bucks", "sport": "NBA", "region": "MW", "color_1": "ForestGreen", "color_2": "white" },
        { "team": "Minnesota Timberwolves", "sport": "NBA", "region": "MW", "color_1": "Navy", "color_2": "ForestGreen" },
        { "team": "New Orleans Pelicans", "sport": "NBA", "region": "S", "color_1": "Navy", "color_2": "Gold" },
        { "team": "New York Knicks", "sport": "NBA", "region": "NE", "color_1": "RoyalBlue", "color_2": "Orange" },
        { "team": "Oklahoma City Thunder", "sport": "NBA", "region": "W", "color_1": "RoyalBlue", "color_2": "Orange" },
        { "team": "Orlando Magic", "sport": "NBA", "region": "S", "color_1": "RoyalBlue", "color_2": "Black" },
        { "team": "Philadelphia 76ers", "sport": "NBA", "region": "NE", "color_1": "RoyalBlue", "color_2": "Red" },
        { "team": "Phoenix Suns", "sport": "NBA", "region": "W", "color_1": "Purple", "color_2": "Orange" },
        { "team": "Portland Trail Blazers", "sport": "NBA", "region": "W", "color_1": "Red", "color_2": "Black" },
        { "team": "Sacramento Kings", "sport": "NBA", "region": "W", "color_1": "Purple", "color_2": "Black" },
        { "team": "San Antonio Spurs", "sport": "NBA", "region": "S", "color_1": "Black", "color_2": "Silver" },
        { "team": "Toronto Raptors", "sport": "NBA", "region": "NE", "color_1": "Red", "color_2": "Black" },
        { "team": "Utah Jazz", "sport": "NBA", "region": "W", "color_1": "Navy", "color_2": "Yellow" },
        { "team": "Washington Wizards", "sport": "NBA", "region": "NE", "color_1": "Navy", "color_2": "Red" },
        { "team": "Anaheim Ducks", "sport": "NHL", "region": "W", "color_1": "Orange", "color_2": "Black" },
        { "team": "Utah Hockey Club", "sport": "NHL", "region": "W", "color_1": "DeepSkyBlue", "color_2": "Black" },
        { "team": "Boston Bruins", "sport": "NHL", "region": "NE", "color_1": "Black", "color_2": "Gold" },
        { "team": "Buffalo Sabres", "sport": "NHL", "region": "NE", "color_1": "Navy", "color_2": "Gold" },
        { "team": "Calgary Flames", "sport": "NHL", "region": "W", "color_1": "Red", "color_2": "Yellow" },
        { "team": "Carolina Hurricanes", "sport": "NHL", "region": "S", "color_1": "Red", "color_2": "Black" },
        { "team": "Chicago Blackhawks", "sport": "NHL", "region": "MW", "color_1": "Red", "color_2": "Black" },
        { "team": "Colorado Avalanche", "sport": "NHL", "region": "W", "color_1": "Maroon", "color_2": "Blue" },
        { "team": "Columbus Blue Jackets", "sport": "NHL", "region": "MW", "color_1": "Navy", "color_2": "Red" },
        { "team": "Dallas Stars", "sport": "NHL", "region": "S", "color_1": "Green", "color_2": "Black" },
        { "team": "Detroit Red Wings", "sport": "NHL", "region": "MW", "color_1": "Red", "color_2": "White" },
        { "team": "Edmonton Oilers", "sport": "NHL", "region": "W", "color_1": "RoyalBlue", "color_2": "Orange" },
        { "team": "Florida Panthers", "sport": "NHL", "region": "S", "color_1": "Red", "color_2": "Navy" },
        { "team": "Los Angeles Kings", "sport": "NHL", "region": "W", "color_1": "Black", "color_2": "Silver" },
        { "team": "Minnesota Wild", "sport": "NHL", "region": "MW", "color_1": "ForestGreen", "color_2": "Red" },
        { "team": "Montreal Canadiens", "sport": "NHL", "region": "NE", "color_1": "Red", "color_2": "Blue" },
        { "team": "Nashville Predators", "sport": "NHL", "region": "S", "color_1": "Gold", "color_2": "Navy" },
        { "team": "New Jersey Devils", "sport": "NHL", "region": "NE", "color_1": "Red", "color_2": "Black" },
        { "team": "New York Islanders", "sport": "NHL", "region": "NE", "color_1": "RoyalBlue", "color_2": "Orange" },
        { "team": "New York Rangers", "sport": "NHL", "region": "NE", "color_1": "RoyalBlue", "color_2": "Red" },
        { "team": "Ottawa Senators", "sport": "NHL", "region": "NE", "color_1": "Red", "color_2": "Black" },
        { "team": "Philadelphia Flyers", "sport": "NHL", "region": "NE", "color_1": "Orange", "color_2": "Black" },
        { "team": "Pittsburgh Penguins", "sport": "NHL", "region": "NE", "color_1": "Black", "color_2": "Gold" },
        { "team": "San Jose Sharks", "sport": "NHL", "region": "W", "color_1": "Teal", "color_2": "Black" },
        { "team": "Seattle Kraken", "sport": "NHL", "region": "W", "color_1": "Teal", "color_2": "Navy" },
        { "team": "St. Louis Blues", "sport": "NHL", "region": "MW", "color_1": "RoyalBlue", "color_2": "Gold" },
        { "team": "Tampa Bay Lightning", "sport": "NHL", "region": "S", "color_1": "RoyalBlue", "color_2": "White" },
        { "team": "Toronto Maple Leafs", "sport": "NHL", "region": "NE", "color_1": "RoyalBlue", "color_2": "White" },
        { "team": "Vancouver Canucks", "sport": "NHL", "region": "W", "color_1": "Navy", "color_2": "Green" },
        { "team": "Vegas Golden Knights", "sport": "NHL", "region": "W", "color_1": "Gold", "color_2": "Black" },
        { "team": "Washington Capitals", "sport": "NHL", "region": "NE", "color_1": "Red", "color_2": "Navy" },
        { "team": "Winnipeg Jets", "sport": "NHL", "region": "W", "color_1": "Navy", "color_2": "Red" },
        { "team": "Arizona Diamondbacks", "sport": "MLB", "region": "W", "color_1": "Red", "color_2": "Black" },
        { "team": "Atlanta Braves", "sport": "MLB", "region": "S", "color_1": "Navy", "color_2": "Red" },
        { "team": "Baltimore Orioles", "sport": "MLB", "region": "AL East", "color_1": "Orange", "color_2": "Black" },
        { "team": "Boston Red Sox", "sport": "MLB", "region": "AL East", "color_1": "Red", "color_2": "Navy" },
        { "team": "Chicago Cubs", "sport": "MLB", "region": "NL Central", "color_1": "RoyalBlue", "color_2": "Red" },
        { "team": "Chicago White Sox", "sport": "MLB", "region": "AL Central", "color_1": "Black", "color_2": "White" },
        { "team": "Cincinnati Reds", "sport": "MLB", "region": "NL Central", "color_1": "Red", "color_2": "White" },
        { "team": "Cleveland Guardians", "sport": "MLB", "region": "AL Central", "color_1": "Navy", "color_2": "Red" },
        { "team": "Colorado Rockies", "sport": "MLB", "region": "NL West", "color_1": "Purple", "color_2": "Black" },
        { "team": "Detroit Tigers", "sport": "MLB", "region": "AL Central", "color_1": "Orange", "color_2": "Navy" },
        { "team": "Houston Astros", "sport": "MLB", "region": "AL West", "color_1": "Navy", "color_2": "Orange" },
        { "team": "Kansas City Royals", "sport": "MLB", "region": "AL Central", "color_1": "RoyalBlue", "color_2": "White" },
        { "team": "Los Angeles Angels", "sport": "MLB", "region": "AL West", "color_1": "Red", "color_2": "Navy" },
        { "team": "Los Angeles Dodgers", "sport": "MLB", "region": "NL West", "color_1": "RoyalBlue", "color_2": "White" },
        { "team": "Miami Marlins", "sport": "MLB", "region": "NL East", "color_1": "Teal", "color_2": "Black" },
        { "team": "Milwaukee Brewers", "sport": "MLB", "region": "NL Central", "color_1": "Navy", "color_2": "Gold" },
        { "team": "Minnesota Twins", "sport": "MLB", "region": "AL Central", "color_1": "Navy", "color_2": "Red" },
        { "team": "New York Mets", "sport": "MLB", "region": "NL East", "color_1": "RoyalBlue", "color_2": "Orange" },
        { "team": "New York Yankees", "sport": "MLB", "region": "AL East", "color_1": "Navy", "color_2": "White" },
        { "team": "Oakland Athletics", "sport": "MLB", "region": "AL West", "color_1": "Green", "color_2": "Gold" },
        { "team": "Philadelphia Phillies", "sport": "MLB", "region": "NL East", "color_1": "Red", "color_2": "White" },
        { "team": "Pittsburgh Pirates", "sport": "MLB", "region": "NL Central", "color_1": "Black", "color_2": "Gold" },
        { "team": "San Diego Padres", "sport": "MLB", "region": "NL West", "color_1": "Brown", "color_2": "Gold" },
        { "team": "San Francisco Giants", "sport": "MLB", "region": "NL West", "color_1": "Orange", "color_2": "Black" },
        { "team": "Seattle Mariners", "sport": "MLB", "region": "AL West", "color_1": "Navy", "color_2": "Teal" },
        { "team": "St. Louis Cardinals", "sport": "MLB", "region": "NL Central", "color_1": "Red", "color_2": "White" },
        { "team": "Tampa Bay Rays", "sport": "MLB", "region": "AL East", "color_1": "Navy", "color_2": "LightBlue" },
        { "team": "Texas Rangers", "sport": "MLB", "region": "AL West", "color_1": "RoyalBlue", "color_2": "Red" },
        { "team": "Toronto Blue Jays", "sport": "MLB", "region": "AL East", "color_1": "RoyalBlue", "color_2": "White" },
        { "team": "Washington Nationals", "sport": "MLB", "region": "NL East", "color_1": "Red", "color_2": "Navy" }



        // Additional teams from NHL, MLB, and NBA can be added here following the same forma
    
]
